AFTER INSERT FREE
STATEMENT CACHE START 
 SQL=INSERT INTO t1 VALUES(?, 1234, 'CSQL'); hits=0 inuse=0
STATEMENT CACHE END
Dropping table
After drop 
STATEMENT CACHE START 
STATEMENT CACHE END
After second time prepare 
STATEMENT CACHE START 
 SQL=INSERT INTO t1 VALUES(?, 1234, 'CSQL'); hits=0 inuse=1
STATEMENT CACHE END
After reusing cached insert stmt
STATEMENT CACHE START 
 SQL=INSERT INTO t1 VALUES(?, 1234, 'CSQL'); hits=0 inuse=0
STATEMENT CACHE END
CREATE TABLE t1 (f1 INT  NOT NULL , f2 INT , f3 VARCHAR (20));
CREATE INDEX t1_idx1_Primary on t1 (  f1  )  HASH  UNIQUE;
INSERT INTO t1 VALUES(1,1, 'First');
INSERT INTO t1 VALUES(2,1, 'Second');
INSERT INTO t1 VALUES(3,1, 'Third');
INSERT INTO t1 VALUES(4,1, 'Fourth');
INSERT INTO t1 VALUES(5,1, 'Fifth');
INSERT INTO t1 VALUES(100,1234, 'CSQL');
INSERT INTO t1 VALUES(200,1234, 'CSQL');
