export MYSQL_DSN=myodbc3
export MYSQL_TDB=mysql
export MYSQL_USER=root
export MYSQL_PASSWORD=

export POSTGRES_DSN=
export POSTGRES_TDB=
export POSTGRES_USER=
export POSTGRES_PASSWORD=

export DB2_DSN=
export DB2_TDB=
export DB2_USER=
export DB2_PASSWORD=

export ORACLE_DSN=
export ORACLE_TDB=
export ORACLE_USER= 
export ORACLE_PASSWORD=

export SYBASE_DSN=
export SYBASE_TDB=
export SYBASE_USER=
export SYBASE_PASSWORD=

export DS1="$MYSQL_DSN $MYSQL_USER $MYSQL_PASSWORD"
export DS2="$POSTGRES_DSN $POSTGRES_USER $POSTGRES_PASSWORD"
export DS3="$DB2_DSN $DB2_USER $DB2_PASSWORD"
export DS4="$ORACLE_DSN $ORACLE_USER $ORACLE_PASSWORD"







