Statement execute failed with error -14
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
[?1034hSQL> select * from t1;
SQL> Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
Statement execute failed with error -14
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
[?1034hSQL> select * from t1;
SQL> 