echo create table t1(f1 tinyint, f2 smallint, f3 int, f4 bigint, f5 char(10), f6 varchar(10), f7 date, f8 time);
create table t1(f1 tinyint, f2 smallint, f3 int, f4 bigint, f5 char(10), f6 varchar(10), f7 date, f8 time);
echo create index hashtiny on t1(f1) hash;
create index hashtiny on t1(f1) hash;
echo create index hashsmall on t1(f2) hash;
create index hashsmall on t1(f2) hash;
echo create index hashint on t1(f3) hash;
create index hashint on t1(f3) hash;
echo create index hashbig on t1(f4) hash;
create index hashbig on t1(f4) hash;
echo create index hashchar on t1(f5) hash;
create index hashchar on t1(f5) hash;
echo create index hashvarchar on t1(f6) hash;
create index hashvarchar on t1(f6) hash;
echo create index hashdate on t1(f7) hash;
create index hashdate on t1(f7) hash;
echo create index hashtime on t1(f8) hash;
create index hashtime on t1(f8) hash;
echo explain plan select * from t1;  
explain plan select * from t1;  
echo explain plan select * from t1 where f1 in (0,2,4);
explain plan select * from t1 where f1 in (0,2,4) ;
echo explain plan select * from t1 where f1 between 2 and 4;
explain plan select * from t1 where f1  between 2 and 4;
echo explain plan select * from t1 where f2 in (0,2,4);;
explain plan select * from t1 where f2 in (0,2,4);
echo explain plan select * from t1 where f2 between 2 and 4;
explain plan select * from t1 where f2 between 2 and 4;
echo explain plan select * from t1 where f3 in (1,2);
explain plan select * from t1 where f3 in (1,2) ;
echo explain plan select * from t1 where f3 between 1 and 4;
explain plan select * from t1 where f3 between 1 and 4;
echo explain plan select * from t1 where f4 in (1,2);
explain plan select * from t1 where f4 in (1,2) ;
echo explain plan select * from t1 where f4 between 1 and 4;
explain plan select * from t1 where f4 between 1 and 4;
echo explain plan select * from t1 where f5 in ('1','2');
explain plan select * from t1 where f5 in ('1','2') ;
echo explain plan select * from t1 where f5 like 'N%';
explain plan select * from t1 where f5 like 'N%';
echo explain plan select * from t1 where f5 like 'N_h';
explain plan select * from t1 where f5 like 'N_h';
echo explain plan select * from t1 where f6 in ('1','2');
explain plan select * from t1 where f6 in ('1','2') ;
echo explain plan select * from t1 where f6 like 'N%';
explain plan select * from t1 where f6 like 'N%';
echo explain plan select * from t1 where f6 like 'N_h';
explain plan select * from t1 where f6 like 'N_h';
echo explain plan select * from t1 where f7 in ('2003-11-12','2003-11-15');
explain plan select * from t1 where f7 in ('2003-11-12','2003-11-15');
echo explain plan select * from t1 where f7 between '2003-11-12' and '2003-11-15';
explain plan select * from t1 where f7 between '2003-11-12' and '2003-11-15';
echo explain plan select * from t1 where f8 in ('03:21:00','03:21:08');
explain plan select * from t1 where f8 in ('03:21:00','03:21:08');
echo explain plan select * from t1 where f8 between '03:21:00' and '03:21:08';
explain plan select * from t1 where f8 between '03:21:00' and '03:21:08';
