echo create table t1(f1 int, f2 int);
create table t1(f1 int, f2 int);
echo create index hashidxt1f1 on t1(f1) hash;
create index hashidxt1f1 on t1(f1) hash;
echo create index hashidxt1f2 on t1(f2) hash;
create index hashidxt1f2 on t1(f2) hash;
echo create table t2(f1 int, f2 int);
create table t2(f1 int, f2 int);
echo create index hashidxt2f1 on t2(f1) hash;
create index hashidxt2f1 on t2(f1) hash;
echo create index hashidxt2f2 on t2(f2) hash;
create index hashidxt2f2 on t2(f2) hash;
echo explain plan select * from t1,t2;
explain plan select * from t1,t2;
echo explain plan select * from t1 inner join t2 on t1.f1=t2.f1;
explain plan select * from t1 inner join t2 on t1.f1=t2.f1;
echo explain plan select * from t1 inner join t2 on t1.f1<=t2.f1;
explain plan select * from t1 inner join t2 on t1.f1<=t2.f1;
echo explain plan select * from t1 inner join t2 on t1.f1!=t2.f1;
explain plan select * from t1 inner join t2 on t1.f1!=t2.f1;
