export CSQL_INSTALL_ROOT=`pwd`
export CSQL_CONFIG_FILE=$CSQL_INSTALL_ROOT/sample/csql.conf
export PATH=$CSQL_INSTALL_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$CSQL_INSTALL_ROOT/lib:/usr/local/lib:$LD_LIBRARY_PATH
export CLASSPATH=$CSQL_INSTALL_ROOT/lib/CSqlJdbcDriver.jar:.:$CLASSPATH
mkdir -p /tmp/csql
mkdir -p /tmp/csql/log
mkdir -p /tmp/csql/db
touch /tmp/csql/csqlds.conf
touch /tmp/csql/csqltable.conf
