echo create table emp(eno int,mgrno int,sal float,deptno int);
create table emp(eno int,mgrno int,sal float,deptno int);
echo insert into emp values(1,3,5000,10);
insert into emp values(1,3,5000,10);
echo insert into emp values(2,4,4000,20);
insert into emp values(2,4,4000,20);
echo insert into emp values(3,NULL,8000,10);
insert into emp values(3,NULL,8000,10);
echo create table dept(deptno int,dname char(10),lid int);
create table dept(deptno int,dname char(10),lid int);
echo insert into dept values(10,'IT',100);
insert into dept values(10,'IT',100);
echo insert into dept values(20,'HR',300);
insert into dept values(20,'HR',300);
echo create table loc(lid int,state char(10));
create table loc(lid int,state char(10));
echo insert into loc values(100,'Orissa');
insert into loc values(100,'Orissa');
echo insert into loc values(200,'Cal');
insert into loc values(200,'Cal');
echo insert into loc values(300,'Calif');
insert into loc values(300,'Calif');
echo select * from emp;
select * from emp;
echo select * from dept;
select * from dept;
echo select * from loc;
select * from loc;
echo select * from emp,dept,loc;
select * from emp,dept,loc;
echo select * from emp,dept,loc where emp.deptno!=dept.deptno AND dept.lid!=loc.lid;
select * from emp,dept,loc where emp.deptno!=dept.deptno AND dept.lid!=loc.lid;
echo select * from emp,dept,loc where NOT(emp.deptno!=dept.deptno AND dept.lid!=loc.lid);
select * from emp,dept,loc where NOT(emp.deptno!=dept.deptno AND dept.lid!=loc.lid);
echo drop table emp;
drop table emp;
echo drop table dept;
drop table dept;
echo drop table loc;
drop table loc;

