echo select * from emp,dept;
select * from emp,dept;
echo select * from emp,dept where emp.dno in(20,30);
select * from emp,dept where emp.dno in(20,30);
echo select * from emp,dept where dept.deptno in(20,30);
select * from emp,dept where dept.deptno in(20,30);
echo select * from emp,dept where emp.dno in(20,30)  and dept.deptno in(20,30);
select * from emp,dept where emp.dno in(20,30)  and dept.deptno in(20,30);
echo select * from emp,dept where emp.dno in(20,30) or dept.deptno in(20,30);
select * from emp,dept where emp.dno in(20,30) or dept.deptno in(20,30);
