echo create table t1(f1 int,f2 int);
create table t1(f1 int,f2 int);
echo insert into t1 values(1,10);
insert into t1 values(1,10);
echo insert into t1 values(2,NULL);
insert into t1 values(2,NULL);
echo insert into t1 values(3,30);
insert into t1 values(3,30);
echo insert into t1 values(5,50);
insert into t1 values(5,50);
echo create table t2(f1 int,f2 int);
create table t2(f1 int,f2 int);
echo insert into t2 values(1,NULL);
insert into t2 values(1,NULL);
echo insert into t2 values(2,20);
insert into t2 values(2,20);
echo insert into t2 values(3,30);
insert into t2 values(3,30);
echo insert into t2 values(4,40);
insert into t2 values(4,40);
echo select * from t1;
select * from t1;
echo select * from t2;
select * from t2;
