CREATE TABLE t1 (f1 INT , f2 INT , f3 INT);
INSERT INTO t1 VALUES(1,1,1);
INSERT INTO t1 VALUES(2,1,2);
INSERT INTO t1 VALUES(3,1,3);
INSERT INTO t1 VALUES(5,2,5);
INSERT INTO t1 VALUES(10,2,10);
INSERT INTO t1 VALUES(100,3,100);
INSERT INTO t1 VALUES(200,3,200);
INSERT INTO t1 VALUES(1000,4,1000);
echo select count(f1) from t1;
select count(f1) from t1;
echo select min(f1) from t1;
select min(f1) from t1;
echo select max(f3) from t1;
select max(f3) from t1;
echo select avg(f1) from t1;
select avg(f1) from t1;
echo select sum(f1) from t1;
select sum(f1) from t1;
echo select count(f1) from t1 group by f2;
select count(f1) from t1 group by f2;
echo select min(f1) from t1 group by f2;
select min(f1) from t1 group by f2;
echo select max(f1) from t1 group by f2;
select max(f1) from t1 group by f2;
echo select avg(f1) from t1 group by f2;
select avg(f1) from t1 group by f2;
echo select sum(f1) from t1 group by f2;
select sum(f1) from t1 group by f2;
echo select min(f1), max(f3), sum(f1) from t1;
select min(f1), max(f3), sum(f1) from t1;
echo select min(f1), f2, max(f3) from t1;
select min(f1), f2, max(f3) from t1;
echo select min(f1), f2, max(f3) from t1 group by f2;
select min(f1), f2, max(f3) from t1 group by f2;
echo select min(f2) from t1 group by f2;
select min(f2) from t1 group by f2;
echo select count(*) from t1;
select count(*) from t1;
echo select count(*) from t1 group by f2;
select count(*) from t1 group by f2;
echo test over
