echo drop table test;
echo create table t1 (f1 integer);
create table t1 (f1 integer);
echo drop table t1;
drop table t1;
echo create table t1 (f1 integer);
create table t1 (f1 integer);
echo drop table t1;
drop table t1;
echo create table t1(f1 int,f2 int);
create table t1(f1 int,f2 int);
echo create index idx1 on t1(f1);
create index idx1 on t1(f1);
echo drop index idx1;
drop index idx1;
echo create index idx1 on t1(f1);
create index idx1 on t1(f1);
echo drop table t1;
drop table t1;
