echo drop table test;
echo create table t1 (f1 integer);
create table t1 (f1 integer);
echo drop table t1;
drop table t1;
echo create table t1 (f1 integer);
create table t1 (f1 integer);
echo drop table t1;
drop table t1;
echo create table t1(f1 int,f2 int);
create table t1(f1 int,f2 int);
echo create index idx1 on t1(f1);
create index idx1 on t1(f1);
echo drop index idx1;
drop index idx1;
echo create index idx1 on t1(f1);
create index idx1 on t1(f1);
echo drop table t1;
drop table t1;
echo create table t1 (f1 integer not null, f2 integer not null,f3 int not null, f4 int not null,f5 int not null, f6 int not null,f7 int not null);
create table t1 (f1 integer not null, f2 integer not null,f3 int not null, f4 int not null,f5 int not null, f6 int not null,f7 int not null);
echo create index idx1 on t1 (f1);
create index idx1 on t1 (f1);
echo create index idx2 on t1 (f2) UNIQUE;
create index idx2 on t1 (f2) UNIQUE;
echo create index idx3 on t1 (f3) PRIMARY;
create index idx3 on t1 (f3) PRIMARY;
echo create index idx4 on t1 (f4) HASH PRIMARY;
create index idx4 on t1 (f4) HASH PRIMARY;
echo create index idx4 on t1 (f5) HASH PRIMARY;
create index idx4 on t1 (f5) HASH PRIMARY;
echo create index idx5 on t1 (f4) HASH PRIMARY;
create index idx5 on t1 (f4) HASH PRIMARY;

echo create index idx5 on t1 (f5) TREE;
create index idx5 on t1 (f5) TREE;
echo create index idx6 on t1 (f6) TREE PRIMARY;
create index idx6 on t1 (f6) TREE PRIMARY;
echo create index idx6 on t1 (f7) TREE PRIMARY;
create index idx6 on t1 (f7) TREE PRIMARY;
echo create index idx7 on t1 (f6) TREE PRIMARY;
create index idx7 on t1 (f6) TREE PRIMARY;

echo drop index idx1;
drop index idx1;
echo drop index idx2;
drop index idx2;
echo drop index idx3;
drop index idx3;
echo drop index idx4;
drop index idx4;
echo drop index idx5;
drop index idx5;
echo drop table t1;
drop table t1;
