echo CREATE TABLE t1(f1 INT DEFAULT 'now', f2 SMALLINT DEFAULT 'now', f3 TINYINT DEFAULT 'now', f4 BIGINT DEFAULT 'now', f5 FLOAT DEFAULT 'now', f6 DOUBLE DEFAULT 'now');
CREATE TABLE t1(f1 INT DEFAULT 'now', f2 SMALLINT DEFAULT 'now', f3 TINYINT DEFAULT 'now', f4 BIGINT DEFAULT 'now', f5 FLOAT DEFAULT 'now', f6 DOUBLE DEFAULT 'now');
