CSQL> HELP;
CSQL Command List
======================================================
SHOW TABLES
SET AUTOCOMMIT ON | OFF
COMMIT | ROLLBACK
SET ISOLATION LEVEL UNCOMMITTED | COMMITTED | REPEATABLE
CREATE TABLE | INDEX ...
DROP TABLE | INDEX ...
INSERT ...
UPDATE ...
DELETE ...
SELECT ...
QUIT
======================================================
