echo CREATE TABLE t1(f1 INT DEFAULT 'CSQL', f2 SMALLINT DEFAULT 'CSQL', f3 TINYINT DEFAULT 'CSQL', f4 BIGINT DEFAULT 'CSQL', f5 FLOAT DEFAULT 'CSQL', f6 DOUBLE DEFAULT 'CSQL',f7 DATE DEFAULT 'CSQL', f8 TIME DEFAULT 'CSQL', f9 TIMESTAMP DEFAULT 'CSQL');
Statement prepare failed with error -19
