echo create table t1(f1 int);
create table t1(f1 int);
echo create index idx1 on t1(f1);
create index idx1 on t1(f1);
echo insert into t1 values(1);
insert into t1 values(1);
echo insert into t1 values(3);
insert into t1 values(3);
echo insert into t1 values(2);
insert into t1 values(2);
echo insert into t1 values(11);
insert into t1 values(11);
echo insert into t1 values(10);
insert into t1 values(10);
echo select * from t1;
select * from t1;
echo set autocommit off;
set autocommit off;
echo insert into t1  values(8);
insert into t1  values(8);
echo insert into t1  values(10);
insert into t1  values(10);
echo select * from t1;
select * from t1;
echo commit;
commit;
echo select * from t1;
select * from t1;
echo rollback;
rollback;
echo select * from t1;
select * from t1;
echo insert into t1 values(12);
insert into t1 values(12);
echo insert into t1 values(11);
insert into t1 values(11);
echo select * from t1;
select * from t1;
echo rollback;
rollback;
echo select * from t1;
select * from t1;
echo commit;
commit;
echo select * from t1;
select * from t1;
echo update t1 set f1=15 where f1=3;
update t1 set f1=15 where f1=3;
echo update t1 set f1=11 where f1=2;
update t1 set f1=11 where f1=2;
echo select * from t1;
select * from t1;
echo rollback;
rollback;
echo select * from t1;
select * from t1;
echo select * from t1 where f1=3;
select * from t1 where f1=3;
echo update t1 set f1=30 where f1=3;
update t1 set f1=30 where f1=3;
echo select * from t1;
select * from t1;
echo commit;
commit;
echo select * from t1;
select * from t1;
echo delete from t1 where f1=30;
delete from t1 where f1=30;
echo select * from t1;
select * from t1;
echo delete from t1 where f1=3;
delete from t1 where f1=3;
echo select * from t1;
select * from t1;
echo rollback;
rollback;
echo select * from t1;
select * from t1;
echo delete from t1 where f1=30;
delete from t1 where f1=30;
echo select * from t1;
select * from t1;
echo delete from t1 where f1=3;
delete from t1 where f1=3;
echo select * from t1;
select * from t1;
echo commit;
commit;
echo select * from t1;
select * from t1;
echo delete  from t1 where f1<=10;
delete  from t1 where f1<=10;
echo select * from t1;
select * from t1;
echo delete from t1;
delete from t1;
echo commit;
commit;
echo select * from t1;
select * from t1;
echo drop table t1;
drop table t1;
echo quit;
quit;
