echo Create table t1(f1 int, f2 char(10000));
Create table t1(f1 int, f2 char(10000));
echo insert into t1 values(1,'wraFASDvgaserrerqwe');
insert into t1 values(1,'wraFASDvgaserrerqwe');
echo insert into t1 values(2,'wraFASDvgaserrerqwe');
insert into t1 values(2,'wraFASDvgaserrerqwe');
echo insert into t1 values(3,'wraFASDvgaserrerqwe');
insert into t1 values(3,'wraFASDvgaserrerqwe');
echo insert into t1 values(4,'wraFASDvgaserrerqwe');
insert into t1 values(4,'wraFASDvgaserrerqwe');
echo insert into t1 values(5,'wraFASDvgaserrerqwe');
insert into t1 values(5,'wraFASDvgaserrerqwe');
echo insert into t1 values(6,'wraFASDvgaserrerqwe');
insert into t1 values(6,'wraFASDvgaserrerqwe');
echo insert into t1 values(7,'wraFASDvgaserrerqwe');
insert into t1 values(7,'wraFASDvgaserrerqwe');
echo insert into t1 values(8,'wraFASDvgaserrerqwe');
insert into t1 values(8,'wraFASDvgaserrerqwe');
echo insert into t1 values(9,'wraFASDvgaserrerqwe');
insert into t1 values(9,'wraFASDvgaserrerqwe');
echo insert into t1 values(10,'wraFASDvgaserrerqwe');
insert into t1 values(10,'wraFASDvgaserrerqwe');
echo select * from t1;
select * from t1;
