/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class csql_jdbc_JSqlStatement */

#ifndef _Included_csql_jdbc_JSqlStatement
#define _Included_csql_jdbc_JSqlStatement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    alloc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_alloc
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_free
  (JNIEnv *, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    freeStmt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_freeStmt
  (JNIEnv *, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setConnectionPtr
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setConnectionPtr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    prepare
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_prepare
  (JNIEnv *, jobject, jstring);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    isSelect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_csql_jdbc_JSqlStatement_isSelect
  (JNIEnv *, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    execute
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_execute
  (JNIEnv *, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    next
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_csql_jdbc_JSqlStatement_next
  (JNIEnv *, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    close
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_csql_jdbc_JSqlStatement_close
  (JNIEnv *, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setShort
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setShort
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setInt
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setLong
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setLong
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setByte
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setByte
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setFloat
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setFloat
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setDouble
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setDouble
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setString
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setDate
 * Signature: (ILjava/sql/Date;)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setDate
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setTime
 * Signature: (ILjava/sql/Time;)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setTime
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setTimestamp
 * Signature: (ILjava/sql/Timestamp;)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setTimestamp
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setBoolean
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setBoolean
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    setNull
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setNull
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    isNull
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_csql_jdbc_JSqlStatement_isNull
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getShort
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_csql_jdbc_JSqlStatement_getShort
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_getInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getLong
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_csql_jdbc_JSqlStatement_getLong
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getByte
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_csql_jdbc_JSqlStatement_getByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_csql_jdbc_JSqlStatement_getFloat
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_csql_jdbc_JSqlStatement_getDouble
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_csql_jdbc_JSqlStatement_getString
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getDate
 * Signature: (I)Ljava/sql/Date;
 */
JNIEXPORT jobject JNICALL Java_csql_jdbc_JSqlStatement_getDate
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getTime
 * Signature: (I)Ljava/sql/Time;
 */
JNIEXPORT jobject JNICALL Java_csql_jdbc_JSqlStatement_getTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getTimestamp
 * Signature: (I)Ljava/sql/Timestamp;
 */
JNIEXPORT jobject JNICALL Java_csql_jdbc_JSqlStatement_getTimestamp
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getBoolean
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_csql_jdbc_JSqlStatement_getBoolean
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    findColumn
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_findColumn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getNoOfFields
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_getNoOfFields
  (JNIEnv *, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getFieldName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_csql_jdbc_JSqlStatement_getFieldName
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getTotalProjFld
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_getTotalProjFld
  (JNIEnv *, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getProjFldType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_getProjFldType
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    isFldNullable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_csql_jdbc_JSqlStatement_isFldNullable
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getProjFldName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_csql_jdbc_JSqlStatement_getProjFldName
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getTableName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_csql_jdbc_JSqlStatement_getTableName
  (JNIEnv *, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getParamFldName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_csql_jdbc_JSqlStatement_getParamFldName
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getTotalparam
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_getTotalparam
  (JNIEnv *, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    getType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_getType
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    isNullable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_csql_jdbc_JSqlStatement_isNullable
  (JNIEnv *, jobject, jint);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    executePro
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_executePro
  (JNIEnv *, jobject);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    preparePro
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_preparePro
  (JNIEnv *, jobject, jstring);

/*
 * Class:     csql_jdbc_JSqlStatement
 * Method:    nextSet
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_csql_jdbc_JSqlStatement_nextSet
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
