#include<SqlStatement.h>
//sqlStmtPtr


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSqlStatement */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JSqlStatement
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_alloc
  (JNIEnv *env, jobject obj)
{
    jclass cls;
    jfieldID fid;

    SqlStatement *stmt = new SqlStatement();

    cls = env->GetObjectClass( obj );
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    env->SetLongField( obj, fid, (jlong) stmt );
    return;
}

/*
 * Class:     JSqlStatement
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_free
  (JNIEnv *env, jobject obj)
{
    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass(obj);
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );
    delete stmt;
    return;
}

/*
 * Class:     JSqlStatement
 * Method:    setConnectionPtr
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setConnectionPtr
  (JNIEnv *env, jobject obj, jlong conn)
{

    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass(obj);
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid);
    stmt->setConnection((SqlConnection*) conn);
    return;
}

/*
 * Class:     JSqlStatement
 * Method:    prepare
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_prepare
  (JNIEnv *env, jobject obj, jstring stmt)
{
    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass(obj);
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return(-1);
    }
    SqlStatement *s = (SqlStatement*) env->GetLongField( obj, fid );
    jboolean isCopy = JNI_TRUE;
    char *stmtString = (char*) env->GetStringUTFChars(stmt, &isCopy );
    int rv = s->prepare(stmtString);
    return rv;
}

/*
 * Class:     JSqlStatement
 * Method:    isSelect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_csql_jdbc_JSqlStatement_isSelect
  (JNIEnv *env, jobject obj)
{
    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass(obj);
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return(-1);
    }
    SqlStatement *s = (SqlStatement*) env->GetLongField( obj, fid );
    return s->isSelect();
}

/*
 * Class:     JSqlStatement
 * Method:    execute
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_execute
  (JNIEnv *env, jobject obj)
{
    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass(obj);
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return(-1);
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );
    int rowsAffected =0;
    DbRetVal rv = stmt->execute(rowsAffected);
    if (rv != OK) return -1;
    return rowsAffected;
}

/*
 * Class:     JSqlStatement
 * Method:    next
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_csql_jdbc_JSqlStatement_next
  (JNIEnv *env, jobject obj)
{
    jclass cls;
    jfieldID fid;
    cls = env->GetObjectClass(obj);
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return(-1);
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );
    void *tuple = stmt->fetch();
    if (NULL != tuple) return 0; else return 1;
}

/*
 * Class:     JSqlStatement
 * Method:    close
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_csql_jdbc_JSqlStatement_close
  (JNIEnv *env, jobject obj)
{
   //TODO::stmt currently does not support close
    jclass cls;
    jfieldID fid;
    cls = env->GetObjectClass(obj);
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return(-1);
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );
    int rv =0;
    //rv  = stmt->close();
    return rv;
}

/*
 * Class:     JSqlStatement
 * Method:    setShort
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setShort
  (JNIEnv *env, jobject obj, jint position, jshort value)
{
    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass( obj );
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );
    stmt->setShortParam(position, (short) value);
    return;
}

/*
 * Class:     JSqlStatement
 * Method:    setInt
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setInt
  (JNIEnv *env, jobject obj, jint position, jint value)
{
    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass( obj );
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );
    stmt->setIntParam(position, (int) value);
    return;
}

/*
 * Class:     JSqlStatement
 * Method:    setLong
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setLong
  (JNIEnv *env, jobject obj, jint position, jlong value)
{
    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass( obj );
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );
    stmt->setLongParam(position, (long) value);
    return;
}

/*
 * Class:     JSqlStatement
 * Method:    setByte
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setByte
  (JNIEnv *env, jobject obj, jint position, jbyte value)
{
    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass( obj );
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );
    stmt->setByteIntParam(position, (ByteInt) value);
    return;
}
/*
 * Class:     JSqlStatement
 * Method:    setFloat
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setFloat
  (JNIEnv *env, jobject obj, jint position, jfloat value)
{
    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass( obj );
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );
    stmt->setFloatParam(position, (float) value);
    return;
}

/*
 * Class:     JSqlStatement
 * Method:    setDouble
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setDouble
  (JNIEnv *env, jobject obj, jint position, jdouble value)
{
    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass( obj );
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );
    stmt->setDoubleParam(position, (double) value);
    return;
}

/*
 * Class:     JSqlStatement
 * Method:    setString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setString
  (JNIEnv *env, jobject obj, jint position, jstring value)
{
    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass( obj );
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }

    jboolean isCopy = JNI_TRUE;
    char *valueStr = (char*) env->GetStringUTFChars( value, &isCopy );

    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );
    stmt->setStringParam(position, valueStr);
    return;
}

/*
 * Class:     JSqlStatement
 * Method:    setDate
 * Signature: (ILjava/sql/Date;)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setDate
  (JNIEnv *env, jobject obj, jint position, jobject dateObj)

{
    jclass cls, datecls;
    jfieldID fid;
    jmethodID dateMethod;

    cls = env->GetObjectClass( obj );
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );

    // Get date, month, year from java object
    int d, m, y;
    datecls = env->GetObjectClass( dateObj );
    dateMethod = env->GetMethodID( datecls, "getYear", "()I");
    y = env->CallIntMethod( dateObj, dateMethod);
    dateMethod = env->GetMethodID( datecls, "getMonth", "()I");
    m = env->CallIntMethod( dateObj, dateMethod);
    dateMethod = env->GetMethodID( datecls, "getDate", "()I");
    d = env->CallIntMethod( dateObj, dateMethod);

    Date date(y + 1900, m + 1, d);
    stmt->setDateParam(position, date);

    return;
}


/*
 * Class:     JSqlStatement
 * Method:    setTime
 * Signature: (ILjava/sql/Time;)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setTime
  (JNIEnv *env, jobject obj, jint position, jobject timeObj)

{
    jclass cls, timecls;
    jfieldID fid;
    jmethodID timeMethod;

    cls = env->GetObjectClass( obj );
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );

    // Get hour, minures, secs from java object
    int h, m, s;
    timecls = env->GetObjectClass( timeObj );
    timeMethod = env->GetMethodID( timecls, "getHours", "()I");
    h = env->CallIntMethod( timeObj, timeMethod);
    timeMethod = env->GetMethodID( timecls, "getMinutes", "()I");
    m = env->CallIntMethod( timeObj, timeMethod);
    timeMethod = env->GetMethodID( timecls, "getSeconds", "()I");
    s = env->CallIntMethod( timeObj, timeMethod);

    Time time(h, m, s, 0);
    stmt->setTimeParam(position, time);

    return;
}

/*
 * Class:     JSqlStatement
 * Method:    setTimestamp
 * Signature: (ILjava/sql/Timestamp;)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setTimestamp
  (JNIEnv *env, jobject obj, jint position, jobject timeObj)

{
    jclass cls, timecls;
    jfieldID fid;
    jmethodID timeMethod;

    cls = env->GetObjectClass( obj );
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid );

    // Get year, month, day, hour, minutes, secs from java object
    int y, mo, d, h, mn, s;
    timecls = env->GetObjectClass( timeObj );

    timeMethod = env->GetMethodID( timecls, "getYear", "()I");
    y = env->CallIntMethod( timeObj, timeMethod );
    timeMethod = env->GetMethodID( timecls, "getMonth", "()I");
    mo = env->CallIntMethod( timeObj, timeMethod );
    timeMethod = env->GetMethodID( timecls, "getDate", "()I");
    d = env->CallIntMethod( timeObj, timeMethod );
    timeMethod = env->GetMethodID( timecls, "getHours", "()I");
    h = env->CallIntMethod( timeObj, timeMethod);
    timeMethod = env->GetMethodID( timecls, "getMinutes", "()I");
    mn = env->CallIntMethod( timeObj, timeMethod);
    timeMethod = env->GetMethodID( timecls, "getSeconds", "()I");
    s = env->CallIntMethod( timeObj, timeMethod);

    TimeStamp timeStamp(y + 1900, mo + 1, d, h, mn, s, 0);
    stmt->setTimeStampParam(position, timeStamp);

    return;
}

/*
 * Class:     JSqlStatement
 * Method:    setNull
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_setNull
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    getShort
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_csql_jdbc_JSqlStatement_getShort
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlStatement_getInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    getLong
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_csql_jdbc_JSqlStatement_getLong
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    getByte
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_csql_jdbc_JSqlStatement_getByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    getFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_csql_jdbc_JSqlStatement_getFloat
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    getDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_csql_jdbc_JSqlStatement_getDouble
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    getString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_csql_jdbc_JSqlStatement_getString
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    getBoolean
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_csql_jdbc_JSqlStatement_getBoolean
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    getBytes
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_csql_jdbc_JSqlStatement_getBytes
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    getDate
 * Signature: (I)Ljava/sql/Date;
 */
JNIEXPORT jobject JNICALL Java_csql_jdbc_JSqlStatement_getDate
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    getTime
 * Signature: (I)Ljava/sql/Time;
 */
JNIEXPORT jobject JNICALL Java_csql_jdbc_JSqlStatement_getTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    getTimestamp
 * Signature: (I)Ljava/sql/Timestamp;
 */
JNIEXPORT jobject JNICALL Java_csql_jdbc_JSqlStatement_getTimestamp
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlStatement
 * Method:    freeStmt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlStatement_freeStmt
  (JNIEnv *env, jobject obj)
{
    jclass cls;
    jfieldID fid;

    cls = env->GetObjectClass(obj);
    fid = env->GetFieldID( cls, "sqlStmtPtr", "J");
    if (fid == 0)
    {
        jclass Exception = env->FindClass("java/lang/Exception");
        env->ThrowNew(Exception,"JNI: GetFieldID failed.\n");
        return;
    }
    SqlStatement *stmt = (SqlStatement*) env->GetLongField( obj, fid);
    stmt->free();
    return;

}

#ifdef __cplusplus
}
#endif
