/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSqlConnection */

#ifndef _Included_csql_jdbc_JSqlConnection
#define _Included_csql_jdbc_JSqlConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JSqlConnection
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlConnection_alloc
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     JSqlConnection
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_csql_jdbc_JSqlConnection_free
  (JNIEnv *, jobject);

/*
 * Class:     JSqlConnection
 * Method:    connect
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlConnection_connect
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     JSqlConnection
 * Method:    disconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlConnection_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     JSqlConnection
 * Method:    isOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_csql_jdbc_JSqlConnection_isOpen
  (JNIEnv *, jobject);

/*
 * Class:     JSqlConnection
 * Method:    beginTrans
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlConnection_beginTrans
  (JNIEnv *, jobject, jint);

/*
 * Class:     JSqlConnection
 * Method:    commit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlConnection_commit
  (JNIEnv *, jobject);

/*
 * Class:     JSqlConnection
 * Method:    rollback
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_csql_jdbc_JSqlConnection_rollback
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
