table t5 is created with records in target db
Recovering table t5 NULL NULL
Recovering table t6 NULL NULL
<Table Information of all tables>
  <TableInfo> 
    <TableName> t5 </TableName>
      <FieldInfo>
        <FieldName> f1 </FieldName>
        <Type> 0 </Type>
        <Length> 4 </Length>
        <Primary> 0 </Primary>
        <Null> 0 </Null>
        <Default> 0 </Default>
        <DefaultValue>  </DefaultValue>
      </FieldInfo>
      <FieldInfo>
        <FieldName> f2 </FieldName>
        <Type> 0 </Type>
        <Length> 4 </Length>
        <Primary> 1 </Primary>
        <Null> 1 </Null>
        <Default> 0 </Default>
        <DefaultValue>  </DefaultValue>
      </FieldInfo>
  </TableInfo> 
  <TableInfo> 
    <TableName> t6 </TableName>
      <FieldInfo>
        <FieldName> f1 </FieldName>
        <Type> 0 </Type>
        <Length> 4 </Length>
        <Primary> 0 </Primary>
        <Null> 0 </Null>
        <Default> 0 </Default>
        <DefaultValue>  </DefaultValue>
      </FieldInfo>
      <FieldInfo>
        <FieldName> f2 </FieldName>
        <Type> 0 </Type>
        <Length> 4 </Length>
        <Primary> 0 </Primary>
        <Null> 0 </Null>
        <Default> 0 </Default>
        <DefaultValue>  </DefaultValue>
      </FieldInfo>
  </TableInfo> 
</Table Information of all tables>
<Index Information of all Indexs>
    <Index Name> t5_PRIMARY </Index Name> 
        <Index Type> Hash Index </Index Type> 
        <Table Name> t5 </Table Name> 
        <Field Name> f2 </Field Name> 
    <Index Name> t5_t5_f1_key </Index Name> 
        <Index Type> Hash Index </Index Type> 
        <Table Name> t5 </Table Name> 
        <Field Name> f1 </Field Name> 
</Index Information of all Indexs>
<Table Information of all tables>
  <TableInfo> 
    <TableName> t5 </TableName>
      <FieldInfo>
        <FieldName> f1 </FieldName>
        <Type> 0 </Type>
        <Length> 4 </Length>
        <Primary> 0 </Primary>
        <Null> 0 </Null>
        <Default> 0 </Default>
        <DefaultValue>  </DefaultValue>
      </FieldInfo>
      <FieldInfo>
        <FieldName> f2 </FieldName>
        <Type> 0 </Type>
        <Length> 4 </Length>
        <Primary> 1 </Primary>
        <Null> 1 </Null>
        <Default> 0 </Default>
        <DefaultValue>  </DefaultValue>
      </FieldInfo>
  </TableInfo> 
  <TableInfo> 
    <TableName> t6 </TableName>
      <FieldInfo>
        <FieldName> f1 </FieldName>
        <Type> 0 </Type>
        <Length> 4 </Length>
        <Primary> 0 </Primary>
        <Null> 0 </Null>
        <Default> 0 </Default>
        <DefaultValue>  </DefaultValue>
      </FieldInfo>
      <FieldInfo>
        <FieldName> f2 </FieldName>
        <Type> 0 </Type>
        <Length> 4 </Length>
        <Primary> 0 </Primary>
        <Null> 0 </Null>
        <Default> 0 </Default>
        <DefaultValue>  </DefaultValue>
      </FieldInfo>
  </TableInfo> 
</Table Information of all tables>
<Index Information of all Indexs>
    <Index Name> t5_PRIMARY </Index Name> 
        <Index Type> Hash Index </Index Type> 
        <Table Name> t5 </Table Name> 
        <Field Name> f2 </Field Name> 
    <Index Name> t5_t5_f1_key </Index Name> 
        <Index Type> Hash Index </Index Type> 
        <Table Name> t5 </Table Name> 
        <Field Name> f1 </Field Name> 
</Index Information of all Indexs>
