OSNAME = $(shell  uname -s)
JAVAC = javac
TARGETS = ConnTests 
ConnTests: ConnTest1.java ConnTest2.java ConnTest3.java ConnTest4.java ConnTest5.java ConnTest6.java
	javac *.java
clean:
	rm -rf *.class
