OSNAME = $(shell  uname -s)
JAVAC = javac
TARGETS = ConnTest1 ConnTest2 ConnTest3 ConnTest4 ConnTest5 
ConnTest1: ConnTest1.java
	javac ConnTest1.java
ConnTest2: ConnTest2.java
	javac ConnTest2.java
ConnTest3: ConnTest3.java
	javac ConnTest3.java
ConnTest4: ConnTest4.java
	javac ConnTest4.java
ConnTest5: ConnTest5.java
	javac ConnTest5.java
clean:
	rm -rf $(TARGETS)
