echo select f3, avg(f1) from t1 group by f3;
select f3, avg(f1) from t1 group by f3;
echo select f3, min(f2) from t1 group by f3;
select f3, min(f2) from t1 group by f3;
echo select f3, count(f1) from t1 group by f3;
select f3, count(f1) from t1 group by f3;
echo select f3, sum(f2) from t1 group by f3;
select f3, sum(f2) from t1 group by f3;
echo select f3, max(f1) from t1 group by f3;
select f3, max(f1) from t1 group by f3;
echo select f1, avg(f2) from t1 group by f1;
select f1, avg(f2) from t1 group by f1;
echo select f1, count(f3) from t1 group by f1;
select f1, count(f3) from t1 group by f1;
echo select f1, min(f2) from t1 group by f1;
select f1, min(f2) from t1 group by f1;
echo select f1, sum(f3) from t1 group by f1;
select f1, sum(f3) from t1 group by f1;
echo select f1, max(f1) from t1 group by f1;
select f1, max(f1) from t1 group by f1;
echo select f2, avg(f2) from t1 group by f2;
select f2, avg(f2) from t1 group by f2;
echo select f2, count(f2) from t1 group by f2;
select f2, count(f2) from t1 group by f2;
echo select f2, min(f2) from t1 group by f2;
select f2, min(f2) from t1 group by f2;
echo select f2, sum(f2) from t1 group by f2;
select f2, sum(f2) from t1 group by f2;
echo select f2, max(f2) from t1 group by f2;
select f2, max(f2) from t1 group by f2;
