echo CREATE TABLE t1(f1 int,f2 int,f3 char(15));
CREATE TABLE t1(f1 int,f2 int,f3 char(15));
echo INSERT INTO t1 VALUES(1,70,'Nihar Pital');
INSERT INTO t1 VALUES(1,70,'Nihar Pital');
echo INSERT INTO t1 VALUES(2,70,'Bijay Sahoo');
INSERT INTO t1 VALUES(2,70,'Bijay Sahoo');
echo INSERT INTO t1 VALUES(3,60,'Kisor Ambli');
INSERT INTO t1 VALUES(3,60,'Kisor Ambli');
echo INSERT INTO t1 VALUES(2,90,'Jiten Lenka');
INSERT INTO t1 VALUES(2,91,'Jiten Lenka');
echo INSERT INTO t1 VALUES(3,80,'Papu Paital');
INSERT INTO t1 VALUES(3,81,'Papu Paital');
echo INSERT INTO t1 VALUES(1,80,'Bijay Sahoo');
INSERT INTO t1 VALUES(1,80,'Bijay Sahoo');
echo INSERT INTO t1 VALUES(2,70,'Jiten Lenka');
INSERT INTO t1 VALUES(2,70,'Jiten Lenka');
echo INSERT INTO t1 VALUES(1,70,'Bijay Sahoo');
INSERT INTO t1 VALUES(1,72,'Bijay Sahoo');
echo INSERT INTO t1 VALUES(2,70,'Bijay Sahoo');
INSERT INTO t1 VALUES(2,70,'Bijay Sahoo');
echo INSERT INTO t1 VALUES(3,60,'Papu Paital');
INSERT INTO t1 VALUES(3,60,'Papu Paital');
echo INSERT INTO t1 VALUES(1,70,'Nihar Pital');
INSERT INTO t1 VALUES(1,71,'Nihar Pital');
echo SELECT * FROM t1;
SELECT * FROM t1;
echo SELECT f1,sum(f2),count(f2),avg(f2),min(f2),max(f2),count(f3) from t1 GROUP BY f1;
SELECT f1,sum(f2),count(f2),avg(f2),min(f2),max(f2),count(f3) from t1 GROUP BY f1;
echo SELECT f3,count(f1),sum(f2),count(f2),avg(f2),min(f2),max(f2) from t1 GROUP BY f3;
SELECT f3,count(f1),sum(f2),count(f2),avg(f2),min(f2),max(f2) from t1 GROUP BY f3;
echo SELECT f1,sum(f2),count(f2),avg(f2),min(f2),max(f2) from t1 GROUP BY f1,f3;
SELECT f1,sum(f2),count(f2),avg(f2),min(f2),max(f2) from t1 GROUP BY f1,f3;
echo SELECT f1,f3,sum(f2),count(f2),avg(f2),min(f2),max(f2) from t1 GROUP BY f1,f3;
SELECT f1,f3,sum(f2),count(f2),avg(f2),min(f2),max(f2) from t1 GROUP BY f1,f3;
