echo create table emp(id int,name char(20),job char(10),salary double,doj date,deptno int,mgrno int);
create table emp(id int,name char(20),job char(10),salary double,doj date,deptno int,mgrno int);
insert into emp values(1,'Allen','Sales'   ,10000,'2006-03-03',10,4);
insert into emp values(2,'Piter',  'IT'    ,10000,'2005-03-03',20,3);
insert into emp values(3,'Jack' ,'Mkting'  ,9000 ,'2006-03-03',30,6);
insert into emp values(4,'Tom',  'Clerk'   ,7000 ,'2004-03-03',10,1);
insert into emp values(5,'Harry ','IT',25000,'2005-03-03',20,5);
insert into emp values(6,'Dick'  ,'Sales'  ,15000,'2005-03-03',30,7);
insert into emp values(7,'Boyee' ,'Mentain',20000,'2005-03-03',20,2);
insert into emp values(3,'Jack' ,  'IT'    ,9000 ,'2006-03-03',30,6);
insert into emp values(2,'Piter',  'Mkting',10000,'2005-03-03',20,3);
echo select * from emp;
select * from emp;
echo select a.deptno,a.name,b.name from emp as a,emp as b where a.id=b.mgrno;
select a.deptno,a.name,b.name from emp as a,emp as b where a.id=b.mgrno;
echo select a.deptno,a.name,b.name from emp as a,emp as b where a.id=b.mgrno group by a.deptno,a.name,b.name;
select a.deptno,a.name,b.name from emp as a,emp as b where a.id=b.mgrno group by a.deptno,a.name,b.name;
echo select a.deptno,a.name,b.name,count(a.salary),sum(b.salary) from emp as a,emp as b where a.id=b.mgrno group by a.deptno,a.name,b.name;
select a.deptno,a.name,b.name,count(a.salary),sum(b.salary) from emp as a,emp as b where a.id=b.mgrno group by a.deptno,a.name,b.name;
echo select a.deptno,a.name,b.name,count(a.salary),sum(b.salary) from emp as a,emp as b where a.id=b.mgrno group by a.deptno,a.name,b.name having count(a.salary)<2 or count(a.salary)>2;
select a.deptno,a.name,b.name,count(a.salary),sum(b.salary) from emp as a,emp as b where a.id=b.mgrno group by a.deptno,a.name,b.name having count(a.salary)<2 or count(a.salary)>2;
echo select a.deptno,a.name,b.name,count(a.salary),sum(b.salary) from emp as a,emp as b where a.id=b.mgrno group by a.deptno,a.name,b.name having (count(a.salary)<2 or count(a.salary)>2) and sum(b.salary)>15000;
select a.deptno,a.name,b.name,count(a.salary),sum(b.salary) from emp as a,emp as b where a.id=b.mgrno group by a.deptno,a.name,b.name having (count(a.salary)<2 or count(a.salary)>2) and sum(b.salary)>15000;
