echo CREATE TABLE Articles ( ArticleID SMALLINT, ArticleTitle CHAR(30) NOT NULL, Copyright INT NOT NULL,PRIMARY KEY(ArticleID));
CREATE TABLE Articles ( ArticleID SMALLINT, ArticleTitle CHAR(30) NOT NULL, Copyright INT NOT NULL,PRIMARY KEY(ArticleID));
echo INSERT INTO Articles VALUES (12786, 'How write a paper',1934); 
INSERT INTO Articles VALUES (12786, 'How write a paper',1934); 
echo INSERT INTO Articles VALUES (13331, 'Publish a paper  ',1919);
INSERT INTO Articles VALUES (13331, 'Publish a paper  ',1919);
echo INSERT INTO Articles VALUES (14356, 'Sell a paper     ',1966);
INSERT INTO Articles VALUES (14356, 'Sell a paper     ',1966);
echo INSERT INTO Articles VALUES (15729, 'Buy a paper      ',1932);
INSERT INTO Articles VALUES (15729, 'Buy a paper      ',1932);
echo INSERT INTO Articles VALUES (16284, 'Conferences      ',1996);
INSERT INTO Articles VALUES (16284, 'Conferences      ',1996);
echo INSERT INTO Articles VALUES (17695, 'Journal          ',1980);
INSERT INTO Articles VALUES (17695, 'Journal          ',1980);
echo INSERT INTO Articles VALUES (19264, 'Information      ',1992);
INSERT INTO Articles VALUES (19264, 'Information      ',1992);
echo INSERT INTO Articles VALUES (19354, 'AI               ',1993);
INSERT INTO Articles VALUES (19354, 'AI               ',1993);
echo CREATE TABLE Authors (AuthID SMALLINT, AuthorFirstName CHAR(20), AuthorMiddleName CHAR(20), AuthorLastName CHAR(20),PRIMARY KEY(AuthID));
CREATE TABLE Authors (AuthID SMALLINT, AuthorFirstName CHAR(20), AuthorMiddleName CHAR(20), AuthorLastName CHAR(20),PRIMARY KEY(AuthID));
echo INSERT INTO Authors VALUES (1006, 'Henry', 'S.', 'Thompson');
INSERT INTO Authors VALUES (1006, 'Henry', 'S.', 'Thompson');
echo INSERT INTO Authors VALUES(1007, 'Jason', 'Carol', 'Oak');
INSERT INTO Authors VALUES(1007, 'Jason', 'Carol', 'Oak');
echo INSERT INTO Authors VALUES(1008, 'James', NULL, 'Elk');
INSERT INTO Authors VALUES(1008, 'James', NULL, 'Elk');
echo INSERT INTO Authors VALUES(1009, 'Tom', 'M', 'Ride');
INSERT INTO Authors VALUES(1009, 'Tom', 'M', 'Ride');
echo INSERT INTO Authors VALUES(1010, 'Jack', 'K', 'Ken');
INSERT INTO Authors VALUES(1010, 'Jack', 'K', 'Ken');
echo INSERT INTO Authors VALUES(1011, 'Mary', 'G.', 'Lee');
INSERT INTO Authors VALUES(1011, 'Mary', 'G.', 'Lee');
echo INSERT INTO Authors VALUES(1012, 'Annie', NULL, 'Peng');
INSERT INTO Authors VALUES(1012, 'Annie', NULL, 'Peng');
echo INSERT INTO Authors VALUES(1013, 'Alan', NULL, 'Wang');
INSERT INTO Authors VALUES(1013, 'Alan', NULL, 'Wang');
echo INSERT INTO Authors VALUES(1014, 'Nelson', NULL, 'Yin');
INSERT INTO Authors VALUES(1014, 'Nelson', NULL, 'Yin');
echo CREATE TABLE AuthorArticle (AuthID SMALLINT NOT NULL, ArticleID SMALLINT NOT NULL,FOREIGN KEY(AuthID) REFERENCES Authors(AuthID), FOREIGN KEY(ArticleID) REFERENCES Articles(ArticleID));
CREATE TABLE AuthorArticle (AuthID SMALLINT NOT NULL, ArticleID SMALLINT NOT NULL,FOREIGN KEY(AuthID) REFERENCES Authors(AuthID), FOREIGN KEY(ArticleID) REFERENCES Articles(ArticleID));
echo INSERT INTO AuthorArticle VALUES (1006, 14356); 
INSERT INTO AuthorArticle VALUES (1006, 14356); 
echo INSERT INTO AuthorArticle VALUES (1008, 15729); 
INSERT INTO AuthorArticle VALUES (1008, 15729); 
echo INSERT INTO AuthorArticle VALUES (1009, 12786); 
INSERT INTO AuthorArticle VALUES (1009, 12786); 
echo INSERT INTO AuthorArticle VALUES (1010, 17695);
INSERT INTO AuthorArticle VALUES (1010, 17695);
echo INSERT INTO AuthorArticle VALUES (1011, 15729); 
INSERT INTO AuthorArticle VALUES (1011, 15729); 
echo INSERT INTO AuthorArticle VALUES (1012, 19264); 
INSERT INTO AuthorArticle VALUES (1012, 19264); 
echo INSERT INTO AuthorArticle VALUES (1012, 19354); 
INSERT INTO AuthorArticle VALUES (1012, 19354); 
echo INSERT INTO AuthorArticle VALUES (1014, 16284);
INSERT INTO AuthorArticle VALUES (1014, 16284);
echo SELECT * FROM Articles;
SELECT * FROM Articles;
echo SELECT * FROM Authors;
SELECT * FROM Authors;
echo SELECT * FROM AuthorArticle;
SELECT * FROM AuthorArticle;
echo SELECT ArticleTitle, Copyright FROM Articles  LEFT JOIN AuthorArticle  ON Articles.ArticleID=AuthorArticle.ArticleID LEFT JOIN Authors ON AuthorArticle.AuthID=Authors.AuthID;
SELECT ArticleTitle, Copyright FROM Articles  LEFT JOIN AuthorArticle  ON Articles.ArticleID=AuthorArticle.ArticleID LEFT JOIN Authors ON AuthorArticle.AuthID=Authors.AuthID;
