OSNAME = $(shell  uname -s)
JAVAC = javac
TARGETS = StmtTests 
StmtTests:	StmtTest1.java StmtTest2.java StmtTest3.java StmtTest4.java \
			StmtTest5.java  StmtTest6.java
	javac Stmt*.java
	chmod +x *.ksh
clean:
	rm -rf *.class
