OSNAME = $(shell  uname -s)
JAVAC = javac
TARGETS = StmtTests 
StmtTests:	StmtTest1.java StmtTest2.java StmtTest3.java StmtTest4.java \
		StmtTest5.java StmtTest6.java StmtTest7.java StmtTest8.java \
		StmtTest9.java JoinPara.java InnerJoinPara.java AggPara.java

	javac *.java
	chmod +x *.ksh
clean:
	rm -rf *.class
