OSNAME = $(shell  uname -s)
JAVAC = javac
TARGETS = Test1 Test2 Test3
Test1: Test1.java
	javac Test1.java
Test2: Test2.java
	javac Test2.java
Test3: Test3.java
	javac Test3.java
clean:
	rm -rf $(TARGETS)
