echo Create table t1(f1 int, f2 varchar(15) default 'CSQL');
Create table t1( f1 int, f2 varchar(15) default 'CSQL');
echo insert into t1 values(1,'Lakshya1');
insert into t1 values(1,'Lakshya1');
echo insert into t1 values(2,NULL);
insert into t1 values(2,NULL);
echo insert into t1 values(3,'Lakshya3');
insert into t1 values(3,'Lakshya3');
echo insert into t1 values(4,NULL);
insert into t1 values(4,NULL);
echo insert into t1(f1) values(5);
insert into t1(f1) values(5);
echo select * from t1;
select * from t1;
echo select * from t1 where f2='CSQL';
select * from t1 where f2='CSQL';
echo update t1 set f2=NULL where f2='Lakshya3';
update t1 set f2=NULL where f2='Lakshya3';
echo select * from t1;
select * from t1;
echo select * from t1 where f2 IS NULL;
select * from t1 where f2 IS NULL;
