echo CREATE TABLE t1 (f1 INT , f2 VARCHAR (12));
CREATE TABLE t1 (f1 INT , f2 VARCHAR (12));
INSERT INTO t1 VALUES(1, 'ABCDE');
INSERT INTO t1 VALUES(2, 'ABCDF');
INSERT INTO t1 VALUES(3, 'ABCDG');
INSERT INTO t1 VALUES(4, 'ABCDH');
INSERT INTO t1 VALUES(5, 'ABCDI');
INSERT INTO t1 VALUES(6, 'NBCDE');
INSERT INTO t1 VALUES(7, 'NBCDF');
INSERT INTO t1 VALUES(8, 'NBCDG');
INSERT INTO t1 VALUES(9, 'NBCDH');
INSERT INTO t1 VALUES(10, 'NBCDI');
echo select * from t1;
select * from t1;
echo delete from t1 where f2='NBCDI';
delete from t1 where f2='NBCDI';
echo select * from t1;
select * from t1;
echo delete from t1 where f2>'NBCDG';
delete from t1 where f2>'NBCDG';
echo select * from t1;
select * from t1;
echo delete from t1 where f2>='NBCDF';
delete from t1 where f2>='NBCDF';
echo select * from t1;
select * from t1;
echo delete from t1 where f2<'ABCDF';
delete from t1 where f2<'ABCDF';
echo select * from t1;
select * from t1;
echo delete from t1 where f2<='ABCDH';
delete from t1 where f2<='ABCDH';
echo select * from t1;
select * from t1;
echo delete from t1 where f2!='NBCDE';
delete from t1 where f2!='NBCDE';
echo select * from t1;
select * from t1;
