echo CREATE TABLE t1 (f1 INT , f2 VARCHAR (12));
CREATE TABLE t1 (f1 INT , f2 VARCHAR (12));
INSERT INTO t1 VALUES(1, 'ABCDE');
INSERT INTO t1 VALUES(2, 'ABCDF');
INSERT INTO t1 VALUES(3, 'NBCDGH');
INSERT INTO t1 VALUES(4, 'NABCDIJ');
INSERT INTO t1 VALUES(5, 'PQRST');
INSERT INTO t1 VALUES(6, 'NIHAR');
INSERT INTO t1 VALUES(7, 'RAHUL');
echo select * from t1;
select * from t1;
echo DELETE FROM t1 where f2 LIKE 'ABCD%';
DELETE FROM t1 where f2 LIKE 'ABCD%';
echo select * from t1;
select * from t1;
echo DELETE FROM t1 where f2 LIKE '_BCD%';
DELETE FROM t1 where f2 LIKE '_BCD%';
echo select * from t1;
select * from t1;
echo DELETE FROM t1 where f2 in ('NIHAR','rahul','CSQL1');
DELETE FROM t1 where f2 in ('NIHAR','rahul','CSQL1');
echo select * from t1;
select * from t1;
