
#ifndef FUNCTION_H 
#define FUNCTION_H

enum FunctionType
{
    UNKNOWN_FUNCTION =-1,
    DATEDIFF,
    TIMEDIFF,
    DATEADDWITHYEAR,
    DATEADDWITHMON,
    DATEADDWITHDAY,
    DATESUBWITHYEAR,
    DATESUBWITHMON,
    DATESUBWITHDAY,
    TIMEADDWITHHOUR,
    TIMEADDWITHMIN,
    TIMEADDWITHSEC,
    TIMESUBWITHHOUR,
    TIMESUBWITHMIN,
    TIMESUBWITHSEC,
    TIMESTAMPADDWITHYEAR,
    TIMESTAMPADDWITHMON,
    TIMESTAMPADDWITHDAY,
    TIMESTAMPSUBWITHYEAR,
    TIMESTAMPSUBWITHMON,
    TIMESTAMPSUBWITHDAY,
    TIMESTAMPADDWITHHOUR,
    TIMESTAMPADDWITHMIN,
    TIMESTAMPADDWITHSEC,
    TIMESTAMPSUBWITHHOUR,
    TIMESTAMPSUBWITHMIN,
    TIMESTAMPSUBWITHSEC,
    TIMESTAMPDIFFYEAR,
    TIMESTAMPDIFFMON,
    TIMESTAMPDIFFDAY,
    TIMESTAMPDIFFHOUR,
    TIMESTAMPDIFFMIN,
    TIMESTAMPDIFFSEC,
    EXTRACTYEARFROMDAY,
    EXTRACTMONFROMDAY,
    EXTRACTDAYFROMDAY,
    EXTRACTYEARFROMTIMESTAMP,
    EXTRACTMONFROMTIMESTAMP,
    EXTRACTDAYFROMTIMESTAMP,
    EXTRACTHOURFROMTIME,
    EXTRACTMINFROMTIME,
    EXTRACTSECFROMTIME,
    EXTRACTHOURFROMTIMESTAMP,
    EXTRACTMINFROMTIMESTAMP,
    EXTRACTSECFROMTIMESTAMP

};
#endif
