OSNAME = $(shell  uname -s)
JAVAC = javac
TARGETS = ConnTests 
TARGETS:ConnTest1.java  ConnTest2.java  ConnTest3.java  \
		ConnTest4.java ConnTest5.java ConnTest6.java \
		ConnTest7.java ConnTest8.java ConnTest9.java \
		ConnTest10.java ConnTest11.java ConnTest12.java ConnTest13.java \
		ConnTest14.java ConnTest15.java ConnTest16.java ConnTest17.java \
		ConnTest18.java ConnTest19.java ConnTest20.java 
	${JAVAC} *.java
	chmod +x *.ksh
clean:
	rm -rf *.class
