OSNAME = $(shell  uname -s)
JAVAC = javac
TARGETS = ConnTests 
TARGETS:ConnTest01.java  ConnTest02.java  ConnTest03.java  \
		ConnTest04.java ConnTest05.java ConnTest06.java ConnTest07.java \
		ConnTest08.java ConnTest09.java ConnTest10.java  
	${JAVAC} *.java
	chmod +x *.ksh
clean:
	rm -rf *.class
