echo create table t1(f1 int, f2 varchar(10), primary key(f1));
create table t1(f1 int, f2 varchar(10), primary key(f1));
echo create table t2(f1 int, f2 varchar(10), foreign key(f1) references t1(f1));
create table t2(f1 int, f2 varchar(10), foreign key(f1) references t1(f1));
insert into t1 values(1,'CSQL1');
insert into t1 values(2,'CSQL2');
insert into t2 values(1,'Nihar');
insert into t2 values(2,'Bijay');
insert into t2 values(1,'Kishor');
insert into t2 values(2,'Jitendra');
echo select * from t1;
select * from t1;
echo select * from t2;
select * from t2;
echo truncate table t1;
truncate table t1;
echo select * from t1;
select * from t1;
echo truncate table t2;
truncate table t2;
echo truncate table t1;
truncate table t1;
echo select * from t1;
select * from t1;
echo select * from t2;
select * from t2;
